
/*consulta todas las marcas de productos q se vendio x cada marca*/
select 
ARTICULO.COD_ARTICULO as Código,
ARTICULO.ARTICULOS_NOMBRE as Nombre,
ARTICULO.ARTICULOS_PRECIO as Precio,
sum(DETALLE_VENTA.COD_CANTIDAD) as Articulos_Vendidos
from ARTICULO
inner join DETALLE_VENTA on DETALLE_VENTA.COD_ARTICULO=ARTICULO.COD_ARTICULO
group by 
Código,
Nombre,
Precio;


/*tecnicos cuanto de ingreso hizo por marca*/
select 
EMPLEADO.EMPLEADO_NOMBRES AS Nombre_Tecnico,
MANTENIMIENTO.MANTENIMIENTO_COSTO as Precio,
MANTENIMIENTO.MANTENIMIENTO_DESCRIPCION as descripcion,
sum(DETALLE_MANTENIMIENTO.COD_MANTENIMIENTO) as Articulos_Vendidos,
SUM(DETALLE_MANTENIMIENTO.COD_MANTENIMIENTO*MANTENIMIENTO.MANTENIMIENTO_COSTO) AS TOTAL
from MANTENIMIENTO
inner join DETALLE_MANTENIMIENTO on DETALLE_MANTENIMIENTO.COD_ARTICULO=DETALLE_MANTENIMIENTO.COD_ARTICULO
INNER JOIN EMPLEADO ON EMPLEADO.COD_EMPLEADO = EMPLEADO.COD_EMPLEADO
group by 
Nombre_Tecnico,
precio,
descripcion;


/*vendedores cuanto ingreso hizo por marca*/
select 
EMPLEADO.EMPLEADO_NOMBRES AS NOMBRE1,
ARTICULO.COD_ARTICULO as Código,
ARTICULO.ARTICULOS_NOMBRE as Nombre,
ARTICULO.ARTICULOS_PRECIO as Precio,
sum(DETALLE_VENTA.COD_CANTIDAD) as Articulos_Vendidos,
SUM(DETALLE_VENTA.COD_CANTIDAD*ARTICULO.ARTICULOS_PRECIO) AS TOTAL
from ARTICULO
inner join DETALLE_VENTA on DETALLE_VENTA.COD_ARTICULO=ARTICULO.COD_ARTICULO
INNER JOIN EMPLEADO ON EMPLEADO.COD_EMPLEADO = EMPLEADO.COD_EMPLEADO
group by 
NOMBRE1,
Código,
Nombre,
Precio;
/*clientes cuantos productos ha comprado*/

select CLIENTE.ID_CLIENTE as CEDULA,
CLIENTE.CLIENTE_NOMBRES AS NOMBRE,
CLIENTE.CLIENTES_APELLIDOS AS APELLIDOS,
count(VENTA.COD_VENTA) as COMPRAS_TOTAL
from PUBLIC.CLIENTE
inner join VENTA on VENTA.ID_CLIENTE=CLIENTE.ID_CLIENTE
group by 
CEDULA,
NOMBRE,
APELLIDOS;

